Feature/tutorial
UQcsse3200/2023-studio-2 pull request #386
Opened 2023-10-02 05:50 UTC by NotRaghavAggarwal

Added tutorial functionality. Please approve <3 Thanks

2023-10-02 11:02 UTC, Minirobbo requested changes
For this to be pulled to main I think it would be good to see some actual dialogue added, possibly using the existing dialogue boxes so there is consistent UI throughout the game. I have pushed some code to fix the dialogue not showing.

2023-10-02 16:44 UTC, connor-golin commented
what does the tutorial currently do? 
I spawned in and theres not much other than the text box in the bottom right.

please add more details to your pr description

2023-10-04 03:52 UTC, Foref commented on source/core/assets/saves/savefile.json
Delete this file to resolve this specific conflict

2023-10-04 04:14 UTC, NotRaghavAggarwal commented on source/core/assets/saves/savefile.json
removed

2023-10-04 10:44 UTC, rachitchaurasia commented
Generated new pull request from tut2 branch that's already merged into main, so closing this one.

2023-10-04 10:44 UTC, closed without merging