Extractor team
UQcsse3200/2023-studio-2 pull request #393
Opened 2023-10-03 04:38 UTC by neil-nb

Redid the main menu screen, among other things like re-refining ship sprite. (Most of the things I did, I did in other people's branches so this is not a good representation of the work I did)

2023-10-03 06:30 UTC, s4697858 commented on source/core/assets/configs/player.json
This file probably shouldn't have been added to the commit

2023-10-03 06:32 UTC, s4697858 requested changes, later dismissed
The only issue is the change to player.json. Revert the health back to 100 and this should be good to merge

2023-10-04 08:52 UTC, rowan-gray approved these changes
Menu looks much better

2023-10-04 09:38 UTC, kk4w4i approved these changes
lgtm

2023-10-04 09:56 UTC, samv26 approved these changes
Nice

2023-10-04 09:56 UTC, samv26 approved these changes
good

2023-10-04 09:57 UTC, samv26 approved these changes
Nice

2023-10-04 09:59 UTC, samv26 approved these changes
G

2023-10-04 09:59 UTC, merged